---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-configmap
  labels:
    component: kibana
data:
  kibana.yml: |-
    # Default Kibana configuration from kibana-docker.
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch:9200
    # custom configuration
    logging.quiet: true
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.2.2
        env:
        - name: CLUSTER_NAME
          value: myesdb
        - name: SERVER_BASEPATH
          value: /kibana
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/kibana/config
      volumes:
      - name: config-volume
        configMap:
          name: kibana-configmap
          items:
            - key: kibana.yml
              path: kibana.yml
